package myDataset

import org.apache.spark.sql.types._

object CarSchema {
  val schema = StructType(Array(
    StructField("vin", StringType),
    StructField("back_legroom", StringType),
    StructField("bed", StringType),
    StructField("bed_height", StringType),
    StructField("bed_length", StringType),
    StructField("body_type", StringType),
    StructField("cabin", StringType),
    StructField("city", StringType),
    StructField("city_fuel_economy", StringType),
    StructField("combine_fuel_economy", StringType),
    StructField("daysonmarket", StringType),
    StructField("dealer_zip", StringType),
    StructField("description", StringType),
    StructField("engine_cylinders", StringType),
    StructField("engine_displacement", StringType),
    StructField("engine_type", StringType),
    StructField("exterior_color", StringType),
    StructField("fleet", StringType),
    StructField("frame_damaged", StringType),
    StructField("franchise_dealer", StringType),
    StructField("franchise_make", StringType),
    StructField("front_legroom", StringType),
    StructField("fuel_tank_volume", StringType),
    StructField("fuel_type", StringType),
    StructField("has_accidents", StringType),
    StructField("height", StringType),
    StructField("highway_fuel_economy", StringType),
    StructField("horsepower", StringType),
    StructField("interior_color", StringType),
    StructField("isCab", StringType),
    StructField("is_certified", StringType),
    StructField("is_cpo", StringType),
    StructField("is_new", StringType),
    StructField("is_oemcpo", StringType),
    StructField("latitude", StringType),
    StructField("length", StringType),
    StructField("listed_date", StringType),
    StructField("listing_color", StringType),
    StructField("listing_id", StringType),
    StructField("longitude", StringType),
    StructField("main_picture_url", StringType),
    StructField("major_options", StringType),
    StructField("make_name", StringType),
    StructField("maximum_seating", StringType),
    StructField("mileage", StringType),
    StructField("model_name", StringType),
    StructField("owner_count", StringType),
    StructField("power", StringType),
    StructField("price", StringType),
    StructField("salvage", StringType),
    StructField("savings_amount", StringType),
    StructField("seller_rating", StringType),
    StructField("sp_id", StringType),
    StructField("sp_name", StringType),
    StructField("theft_title", StringType),
    StructField("torque", StringType),
    StructField("transmission", StringType),
    StructField("transmission_display", StringType),
    StructField("trimId", StringType),
    StructField("trim_name", StringType),
    StructField("vehicle_damage_category", StringType),
    StructField("wheel_system", StringType),
    StructField("wheel_system_display", StringType),
    StructField("wheelbase", StringType),
    StructField("width", StringType),
    StructField("year", IntegerType)
  ))

}
